[package]
name = "finite-state-automaton"
version = "0.1.2"
authors = ["KBR9 <cabero96@protonmail.com>"]
repository = "https://github.com/cbr9/finite-state-automaton"
description = "A minimal DFSA implementation based on Jurafsky & Martin (2009)"
license = "MIT"
edition = "2018"

